### ISSUE TITLE
Result doesn't update correctly when the promise changes

### ISSUE THREAD

**Issue by Vlemert** [lucmartens/composables#2]
When the promise passed to `Result` changes, render is not called with the result of that new promise. This seems to be caused by the `shallowEqual` in `src/equal`, which thinks two different promises are equal because it only checks the keys and values (both an empty array).

Will create a PR with a failing test case soon, needed this issue to refer to from our code.

Current workaround is to make sure the promises passed to Result have a unique key, in our case I added a counter that increases for each promise.

**Comment by lucmartens** [comment]
This has been resolved in v0.2.0, as such I'm closing this issue.
